# Generated by Django 5.1.1 on 2024-09-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('short_description', models.TextField(help_text='This will be shown on the home page.')),
                ('long_description', models.TextField(help_text='This will be shown on the detailed page.')),
                ('infrastructure', models.TextField(verbose_name='Infrastructure of APON')),
                ('membership_affiliation', models.TextField(verbose_name='Membership & Affiliation')),
                ('awards', models.TextField(verbose_name='Awards')),
                ('goal', models.TextField(verbose_name='Goal')),
                ('objectives', models.TextField(verbose_name='Objectives of APON')),
                ('program_activities', models.TextField(verbose_name='Program Activities')),
                ('main_image', models.ImageField(default='path/to/default/main_image.jpg', help_text='Main image for the home page.', upload_to='about_us/')),
                ('additional_images', models.ImageField(blank=True, help_text='Additional images for the detailed page.', null=True, upload_to='about_us/')),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Section',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
