# Generated by Django 5.1.1 on 2024-09-08 04:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='awards',
            field=tinymce.models.HTMLField(verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='goal',
            field=tinymce.models.HTMLField(verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='infrastructure',
            field=tinymce.models.HTMLField(verbose_name='Infrastructure of APON'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='long_description',
            field=tinymce.models.HTMLField(help_text='This will be shown on the detailed page.'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='membership_affiliation',
            field=tinymce.models.HTMLField(verbose_name='Membership & Affiliation'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='objectives',
            field=tinymce.models.HTMLField(verbose_name='Objectives of APON'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='program_activities',
            field=tinymce.models.HTMLField(verbose_name='Program Activities'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='short_description',
            field=tinymce.models.HTMLField(help_text='This will be shown on the home page.'),
        ),
    ]
